---
openapi: 3.0.4
servers:
- description: generated server for Endpoint
  url: ccs.gov.uk
info:
  title: :Endpoint
  description: genearated endpoint for data Endpoint
  version: 0.1.0
  contact:
    email: admin@ccs.gov.uk
  license:
    name: MIT
    url: https://github.com/Crown-Commercial-Service/ccs-data-model/blob/master/LICENSE
tags:
- name: browser
  description: for all users, typically buyers
- name: recorder
  description: for record updaters, often suppliers
paths:
  "/Agreement":
    get:
      summary: search
      tags:
      - browser
      operationId: search-Agreement
      description: searches Agreement by name, id or keyword
      parameters:
      - "$ref": "#/components/parameters/q_name"
      - "$ref": "#/components/parameters/q_id"
      - "$ref": "#/components/parameters/q_keyword"
      - "$ref": "#/components/parameters/q_limit"
      - "$ref": "#/components/parameters/q_skip"
      responses:
        '200':
          "$ref": "#/components/responses/Agreements"
        4XX:
          description: error TODO
    post:
      summary: put
      tags:
      - recorder
      operationId: create-Agreement
      description: add a new Agreement and retreive copy of it
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Agreement"
        description: body should be the new Agreement
      responses:
        '200':
          "$ref": "#/components/responses/Agreement"
        4XX:
          description: error TODO
  "/Agreement/{id}":
    get:
      summary: get a Agreement
      tags:
      - recorder
      description: retrieve Agreement by id
      parameters:
      - "$ref": "#/components/parameters/id"
      responses:
        '200':
          "$ref": "#/components/responses/Agreement"
        4XX:
          description: error TODO
    post:
      summary: post
      tags:
      - recorder
      operationId: revise-Agreement
      description: update an existing Agreement given its id
      parameters:
      - "$ref": "#/components/parameters/id"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Agreement"
        description: body should be the updated Agreement
      responses:
        '200':
          "$ref": "#/components/responses/Agreement"
        4XX:
          description: error TODO
components:
  schemas:
    Agreement:
      type: object
      required:
      - id
      - name
      properties:
        :kind:
          type: string
          enum:
          - Framework
          - Lot
          - Contract
        :id:
          type: string
          example: RM3541
        :keyword:
          type: array
          items:
            type: string
        :name:
          type: string
        :long_name:
          type: string
        :version:
          type: string
        :status:
          type: string
          enum:
          - Live
          - Inactive
          - Future
          - Planned
          - Underway
          - Withdrawn
          - Ended
        :pillar:
          type: string
        :duration:
          type: integer
        :category:
          type: string
        :start_date:
          type: string
          format: date
        :end_date:
          type: string
          format: date
        :original_end_date:
          type: string
          format: date
        :description:
          type: string
        :offerType:
          type: string
        :part_of_id:
          type: string
        :conforms_to_id:
          type: string
        :item_type:
          type: array
          items:
            "$ref": "#/components/schemas/ItemType"
        :min_value:
          type: integer
        :max_value:
          type: integer
    ItemType:
      type: object
      required:
      - id
      - name
      properties:
        :id:
          type: string
        :description:
          type: string
        :keyword:
          type: array
          items:
            type: string
        :scheme_id:
          type: string
          enum:
          - CPV
          - CPVS
          - GSIN
          - UNSPSC
          - CPC
        :code:
          type: string
        :unit_scheme:
          type: string
          enum:
          - UNCEFACT
          - QUDT
        :unit:
          type: string
  parameters:
    q_name:
      name: q_name
      in: query
      description: optional search parameter
      schema:
        type: string
    q_id:
      name: q_id
      in: query
      description: optional search parameter
      schema:
        type: string
    q_keyword:
      name: q_keyword
      in: query
      description: optional search parameter
      schema:
        type: string
    q_title:
      name: q_title
      in: query
      description: optional search parameter
      schema:
        type: string
    id:
      name: id
      in: path
      required: true
      description: optional id parameter
      schema:
        type: string
    q_limit:
      name: q_limit
      in: query
      description: optional control parameter
      schema:
        type: integer
        format: int32
        minimum: 0
        maximum: 200
    q_skip:
      name: q_skip
      in: query
      description: optional control parameter
      schema:
        type: integer
        format: int32
        minimum: 0
  responses:
    Agreement:
      description: Agreement matching id
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/Agreement"
    Agreements:
      description: array of Agreements matching id
      content:
        application/json:
          schema:
            type: array
            items:
              "$ref": "#/components/schemas/Agreement"
